### ISSUE TITLE
Creating Stake Pool pledge wallet keys

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#71]
**Tasks:**

- [x] Generating staking cli keys
- [x] Generating payment HW keys
- [x] Building a Payment (pledge) address (from payment and staking public keys)
- [x] Building a stake Address
- [x] Create the staking registration certificate
- [x] Checking if we have generated the files
- [x] Check the pledge address (where you will have to send the funds
- [x] Testing  generated addresses and pledging

**Comment by andreassosilo** [comment]
Done. All of the necessary stuff already created. Will send these files to Lauris.

Eastern Town Hall - C3ETH Stake Pool
========================

1. Generating staking cli keys
	-. pool.staking.skey
	-. pool.staking.vkey

2. Generating payment HW keys
	-. pool.payment.vkey
	-. pool.payment.hwsfile
	
3. Building a Payment (pledge) address (from payment and staking public keys)
	-. pool.payment.addr
	
4. Building a stake Address
	-. pool.staking.addr 

5. Create the staking registration certificate
	-. pool.staking.cert 
	
6. Check the pledge address (where you will have to send the funds):
	-. addr1qyj5g4nwf2kmy9y0zxwljc6j4h9vz3xrxwsq2a6g2h4tlrcz8asyzr32yfelrmgtjtnpp0g4gstr4xrll9clllhhej9qghgdzq
	
7. Testing generated addresses and pledging
