### ISSUE TITLE
Buy & setup hardware wallet (Ledger Nano S) for C3ETH Stake Pool

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#72]
**Tasks:**

- [x] Buy hardware wallet (Ledger Nano S) for C3ETH Stake Pool
- [x] Setup the hardware wallet
- [ ] Submit invoice to @wolstaeb for treasury accounting

**Comment by andreassosilo** [comment]
**Progress:**

- Already bought via Amazon Germany
- Will arrive on Tuesday, 09 November 2021
- Setup will be done on Tuesday, 09 November 2021

**Comment by wolstaeb** [comment]
Thanks @andreassosilo I was going to ask you to send the invoice, but you're ahead of me. Can you also add a write up  about the stakepool arrangement and any configuation details. A simple markdown file in this repository will be fine. I am considering making this repo private (or use another one for the purpose) to the team so that not everything about our setup is public. Details like the stakepool arrangements warrant this I think.

**Comment by andreassosilo** [comment]
This is the invoice for the Ledger Nano S, as per your request @wolstaeb :
[invoiceLedgerEasternTownHall.pdf](https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/files/7499806/invoiceLedgerEasternTownHall.pdf)

Ledger Nano S is already setup. I will close this ticket and continue to the next progress.

**Comment by wolstaeb** [comment]
Recieved the invoice from @andreassosilo. @andreassosilo can you add the details to the [simple ETH Accounting Sheet](https://docs.google.com/spreadsheets/d/19qnqCYGzqrRlINgvvUoFpe9oCGdVKb1h1XK7jRITpJs/edit?usp=sharing) @cardanoz has set up.
