### ISSUE TITLE
Fill in the necessary information for C3ETH Stake Pool metadata

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#73]
**Tasks:**

- [x] Get necessary information from all Eastern Town Hall Team Members
- [x] Fill in the form
- [x] Prepare the stake pool necessary files for Lauris
- [x] Submit to @FelixfromSwarm and Lauris

**Notes:**

- https://docs.google.com/spreadsheets/d/1Nf2pHK5DNESnQV0UnRdTb--Ofdn8V2moh5cKeLQZgNA/edit#gid=0

**Comment by andreassosilo** [comment]
E-mail sent to Lauris for necessary stake pool generated files. Sent also the filled form.
