### ISSUE TITLE
Build web page for Eastern Town Hall Stake Pool

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#77]
**Tasks:**

- [ ] Ask @wolstaeb for documentation of our web page
- [ ] Collect and add some content for the stake pool page
- [ ] Implement the content using Hugo, etc.
- [ ] Get approval & feedback from Eastern Town Hall Team Member

**Comment by wolstaeb** [comment]
Here are the links @andreassosilo to Hugo and Docsy. The setup instructions (especially using the Docker Container) have not been tested and we need to do more in terms of documenting the release process. 

[Hugo](https://gohugo.io/) and [Docsy](https://www.docsy.dev/)

The steps to add a new page are:

1. Install Hugo/Docsy locally or in a Container.
2. Fork the repository
3. Make changes locally and test.
4. Send a Pull request to the main website repo.
5. PR will be reviewed and merged into the main branch
6. When we are ready to publish any changes to the site the HEAD of the main branch is merged into Release.

Adding a new page without any template changes involves creating a markdown file in a particular location. Start with English ``content\en`` then once the content is finalised we can get translations done.
