### ISSUE TITLE
Adding metadata files to our website & web hosting

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#80]
**Tasks:**

- [x] Discussion with Lauris regarding which files do we need to add
- [x] Get the images, extended.json and metadata.json
- [x] @wolstaeb needs to add it to our website folder
- [x] Inform Lauris and testing metadata in blockchain explorer, such as cardanoscans.io

**Notes:**
https://easterntownhall.com/metadata/c3eth.png
https://easterntownhall.com/metadata/c3eth-64x64.png
https://easterntownhall.com/metadata/c3eth.extended.json
https://easterntownhall.com/metadata/c3eth.metadata.json

**Comment by andreassosilo** [comment]
Done.

Checked in cardanoscans.io and adapools.org:

https://cardanoscan.io/pool/f0a112d12e435e9659f80a41236daf525e08189702a25a7d0876f962

https://adapools.org/pool/f0a112d12e435e9659f80a41236daf525e08189702a25a7d0876f962
