### ISSUE TITLE
Get the pledge into pledge address

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#81]
**Tasks:**

- [x] Test if the pledge address is correct, using 5 ADA
- [x] Get the 2500 ADA pledge from treasury @wolstaeb 
- [x] Recheck if 2500 ADA is received on the hardware wallet
- [x] Inform Lauris so he could setup the staking pool accordingly

**Comment by andreassosilo** [comment]
Screenshot on the pledge received
![c3ethwallet](https://user-images.githubusercontent.com/50327438/141783666-78ad94ec-48c7-43f0-a7a9-3e90a3741672.png)
:
