### ISSUE TITLE
Get access for stake pool dashboard management from Lauris

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#86]
**Tasks:**

- [x] Get access to the C3ETH stake pool dashboard management from Lauris -> app.stakepool247.eu
- [x] Test the access for C3ETH stake pool
- [x] Learn about the dashboard information

**Notes:**
![dashboard](https://user-images.githubusercontent.com/50327438/142738257-d628f00c-e7c8-48ec-8a88-f76c279a9174.png)

**Comment by andreassosilo** [comment]
Done. Already get access to https://app.stakepool247.io/ for our C3ETH Stake Pool.
![laurisDashboard](https://user-images.githubusercontent.com/50327438/143698966-cfe3cb97-fa99-4c99-a39c-8d920ce933f6.PNG)
